name: Build and Test
on: [push, pull_request]
jobs:
  ubuntu:
    strategy:
      matrix:
          version: ["8.0", "8.1", "8.2", "8.3", "8.4", "8.5"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.version}}
      - name: phpize
        run: phpize
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: test
        run: make test TESTS="--show-diff tests"
  windows:
    strategy:
      matrix:
          version: ["8.0", "8.1", "8.2"]
          arch: [x64]
          ts: [nts, ts]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build and test the extension
        uses: php/php-windows-builder/extension@v1
        with:
          php-version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}
          args: --enable-buffer
          run-tests: true
          test-runner-args: "--show-diff tests"
